### ISSUE TITLE
Specify alternative ports to 80:80 

### ISSUE THREAD

**Issue by nodecentral** [PeterDaveHello/ipinfo.tw#10]
Hi

As I’d like to run this docker in host mode , port 80 is already taken, is it possible for me to just change the ports in the Docker compose ?

many thanks

**Comment by PeterDaveHello** [comment]
@nodecentral You can build your own image based on the latest peterdavehello/ipinfo.tw, but change the port in nginx/conf.d/ipinfo.conf

**Comment by nodecentral** [comment]
Ohhh ok, I’ve not built an image before ? Is there an idiot’s guide to how to do that ?

**Comment by PeterDaveHello** [comment]
@nodecentral Not sure if this is something you're looking for:
- https://www.docker.com/101-tutorial
- https://training.play-with-docker.com/

**Comment by PeterDaveHello** [comment]
Close due to no response.
