### ISSUE TITLE
Name of docker-compose service intended?

### ISSUE THREAD

**Issue by shruuub** [PeterDaveHello/ipinfo.tw#16]
Hello, thanks for the great work!
I wondered why the name of the [docker compose service](https://github.com/PeterDaveHello/ipinfo.tw/blob/master/docker-compose.yml#L5) is called tor-socks-proxy.
Of course, it's no real problem and could easily be user changed (like ports listening on 0.0.0.0 too etc.) but I still wondered, since I thought it might be unintended :).

**Comment by PeterDaveHello** [comment]
@shruuub nice catch! It's copied from my another project: https://github.com/PeterDaveHello/tor-socks-proxy, and I missed the name change, will fix it, thanks.
