### ISSUE TITLE
Feature Request: Separate Endpoints for IPv4 and IPv6 Information

### ISSUE THREAD

**Issue by BrettDean** [PeterDaveHello/ipinfo.tw#31]
### Description

This feature request proposes the addition of separate endpoints to retrieve information specifically for IPv4 and IPv6 addresses.

### Proposed Endpoints

- **IPv4 Endpoint:** `https://ipinfo.tw/ipv4`
- **IPv6 Endpoint:** `https://ipinfo.tw/ipv6`

### Motivation

Having dedicated endpoints for IPv4 and IPv6 addresses would offer more flexibility for users who specifically require information about a particular IP version. This separation would enhance the usability and granularity of the service.

**Comment by PeterDaveHello** [comment]
@Dean12321 ipv4.ipinfo.tw and ipv6.ipinfo.tw should be good enough for this purpose?
